version: "3.2"
services:
  api-gateway:
    build: ./api-gateway
    environment: 
      - PORT=8080
      - CLIENTES_SERVICE=http://clientes-service:3000
    ports:
      - "8080:8080"
    networks:
      - bantads-net
  clientes-service: 
    build: ./clientes-service
    environment: 
      - SERVER_PORT=3000
      - SERVER_SERVLET_CONTEXT_PATH=/api/v1/clientes
    networks:
      - bantads-net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - bantads-net

  mysql-database:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "banking"
    ports:
      - "3307:3307"
    volumes:
      - ~/.docker-conf/mysql/data/:/var/lib/mysql/
    networks:
      - bantads-net
networks:
  bantads-net:
    driver: bridge
