version: "3.2"
services:
  api-gateway:
    build: ./api-gateway
    environment: 
      - PORT=8080
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - bantads-net

networks:
  bantads-net:
    driver: bridge